### ISSUE TITLE
conversion to osm

### ISSUE THREAD

**Issue by h4ck3rm1k3** [JamesChevalier/cities#4]
here is a script to convert the cities (in nj) to osm
https://github.com/codefortrenton/school-districts/blob/master/poly2osm.pl

**Comment by JamesChevalier** [comment]
Thanks!

I believe this will create an `.osm` file that holds the *borders* of the city.

The process that I quickly outline at [the bottom of the README](https://github.com/JamesChevalier/cities#how-to-use-the-poly-file) will create an `.osm` file that holds the *full data* of the city.

Semi-related, if anyone needs `.geojson` files from these `.poly` files, you can use [polytogeojson](https://github.com/cschwarz/polytogeojson). Similar to `poly2osm`, this produces a `.geojson` file that holds the *borders* of the city.
